export { getGreetting } from './utils'
export { EmailConfig, SendEmailOptions } from './types'
export { emailConfig } from './email-config'
export { sendGroupMail } from './send-group-mail'
export { sendMail } from './send-mail'
