export enum ERR_CODE {
  UnknownUserEmail            = 'UnknownUserEmail',
  EmailExist                  = 'EmailExist',
  PasswordWrong               = 'PasswordWrong',
  AccountDisabled             = 'AccountDisabled',
  UnauthorizedRequest         = 'UnauthorizedRequest',
  CookieNotAuth               = 'CookieNotAuth',
  InvalidData                 = 'InvalidData',
  InvalidEmail                = 'InvalidEmail',
  Required                    = 'Required',
  AdditionalProperties        = 'AdditionalProperties',
  MinLength                   = 'MinLength',
  MaxLength                   = 'MaxLength',
  Minimum                     = 'Minimum',
  Maximum                     = 'Maximum',
  Const                       = 'Const',
  Format                      = 'Format',
  FormatShouldBe              = 'FormatShouldBe',
  NotBeError                  = 'NotBeError',
  MustBeNumber                = 'MustBeNumber',
  MustBeOneOfSeveral          = 'MustBeOneOfSeveral',
  MustNotBeEmpty              = 'MustNotBeEmpty',
  MustBeLess                  = 'MustBeLess',
  MustBeGreater               = 'MustBeGreater',
  MustBeBool                  = 'MustBeBool',
  MustBeString                = 'MustBeString',
  CannotGetData               = 'CannotGetData',
  FolderMustNotBeFull         = 'FolderMustNotBeFull',
  MustBePermissions           = 'MustBePermissions',
  DevMustBeOneOfSeveral       = 'DevMustBeOneOfSeveral',
  DevMustNotBeEmpty           = 'DevMustNotBeEmpty',
  General                     = 'General',
  GeneratePasswordResetLink   = 'generatePasswordResetLink',
  GuardCSRF                   = 'GuardCSRF',
  BasRequest                  = 'Bad Request',
  'Bad Request'               = 'Bad Request',
  
  // File
  MaxFileSize = 'MaxFileSize',
  // Firebase
  'auth/id-token-expired'          = 'auth/id-token-expired',
  'auth/email-already-exists'      = 'auth/email-already-exists',
  'auth/user-not-found'            = 'auth/user-not-found',
  'auth/wrong-password'            = 'auth/wrong-password',
  'auth/email-already-in-use'      = 'auth/email-already-in-use',
  'auth/invalid-login-credentials' = 'auth/invalid-login-credentials'
}
